language: python
dist: bionic

addons:
  apt:
    packages:
    - ffmpeg

python:
 - 3.5
 - 3.6
 - 3.7
 - 3.8
 - 3.9

install:
 # Install from wheel instead of from source in setup.py to speed up CI
 - pip install lxml

 - pip install pycodestyle pyflakes
 - python setup.py install

script:
 - pyflakes yledl/*.py
 - python setup.py pytest
 - yle-dl --help

after_script:
 - pycodestyle --statistics --count yledl/*.py
