dist: trusty

language: python

python:
 - 2.7
 - 2.6

sudo: false

install:
 - pip install pyflakes pep8
 - python setup.py install

script:
 - pyflakes yledl/yledl.py
 - yle-dl --help

after_script:
 - pep8 --statistics --count yledl/yledl.py
