version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run:
          name: Install test dependencies
          command: pip install pycodestyle pyflakes
      - run:
          name: Install ffmpeg
          command: |
            sudo apt update
            sudo apt install -y ffmpeg
      - run:
          name: pyflakes
          command: pyflakes yledl/*.py
      - run:
          name: Smoke test
          command: yle-dl --help
      - run:
          name: Statistics
          # E266 too many leading ‘#’ for block comment
          # W504 line break after binary operator
          command: |
            pycodestyle --ignore=E266,W504 --max-line-length 100 --statistics --count yledl/*.py || true

  test35:
    docker:
      - image: cimg/python:3.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run: python setup.py test

  test36:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run: python setup.py test

  test37:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run: python setup.py test

  test38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run: python setup.py test

  test39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run: python setup.py test



workflows:
  main:
    jobs:
      - lint
      - test35:
          requires:
            - lint
      - test36:
          requires:
            - lint
      - test37:
          requires:
            - lint
      - test38:
          requires:
            - lint
      - test39:
          requires:
            - lint
